/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cylin' at '9/14/16 7:05 PM' with Gradle 3.0-milestone-1
 *
 * @author cylin, @date 9/14/16 7:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
